
services:
  api:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_DATABASE=filmes
      - DB_AUTH=mysql_native_password
    restart: always
    volumes:
      - ./application:/app/application
